close all;
clear all;
epoch.Year = 2024;
epoch.Month = 10;
epoch.Day = 12;
epoch.Hour = 12;
epoch.Minute = 24;
epoch.Second = 45;
epoch.DecimalYear = decyear(epoch.Year, epoch.Month, epoch.Day, epoch.Hour, epoch.Minute, epoch.Second);
attitude.P0 = 0; 
attitude.Q0 = 0;
attitude.R0 = 0;
satellite.MOI = eye(3);
satellite.InvMOI = inv(satellite.MOI);
